### ISSUE TITLE
Build Fails on Ubuntu

### ISSUE THREAD

**Issue by FrankDJIlek** [bisqwit/nescom#2]
I run "make" but after compiling a couple things, it outputs some errors.
Output:

(xenial)spongbap@localhost:/var/host/media/removable/UNTITLED/nescom-1.2.0$ make
Checking dependencies...
g++ -std=c++1z -Ofast -Wall -Wundef -Wcast-qual -Wpointer-arith -Wconversion -Wwrite-strings -Wsign-compare -Wredundant-decls -Winit-self -Wextra -Wcast-align -Wformat -Woverloaded-virtual -Wno-conversion -DVERSION=\"1.2.0\" -g -pipe  -I.  -c -o assemble.o assemble.cc
g++ -std=c++1z -Ofast -Wall -Wundef -Wcast-qual -Wpointer-arith -Wconversion -Wwrite-strings -Wsign-compare -Wredundant-decls -Winit-self -Wextra -Wcast-align -Wformat -Woverloaded-virtual -Wno-conversion -DVERSION=\"1.2.0\" -g -pipe  -I.  -c -o insdata.o insdata.cc
g++ -std=c++1z -Ofast -Wall -Wundef -Wcast-qual -Wpointer-arith -Wconversion -Wwrite-strings -Wsign-compare -Wredundant-decls -Winit-self -Wextra -Wcast-align -Wformat -Woverloaded-virtual -Wno-conversion -DVERSION=\"1.2.0\" -g -pipe  -I.  -c -o object.o object.cc
object.cc: In member function 'void Object::WriteO65(FILE*)':
object.cc:1343:14: error: expected unqualified-id before '[' token
     for(auto [segtype,segptr]: std::initializer_list<std::pair<SegmentSelection,Segment*>>
              ^
object.cc:1343:14: error: expected ';' before '[' token
object.cc:1343:15: error: 'segtype' was not declared in this scope
     for(auto [segtype,segptr]: std::initializer_list<std::pair<SegmentSelection,Segment*>>
               ^
object.cc:1343:23: error: 'segptr' was not declared in this scope
     for(auto [segtype,segptr]: std::initializer_list<std::pair<SegmentSelection,Segment*>>
                       ^
object.cc: In lambda function:
object.cc:1343:30: error: expected '{' before ':' token
     for(auto [segtype,segptr]: std::initializer_list<std::pair<SegmentSelection,Segment*>>
                              ^
object.cc: In member function 'void Object::WriteO65(FILE*)':
object.cc:1343:30: error: expected ';' before ':' token
object.cc:1343:30: error: expected primary-expression before ':' token
object.cc:1343:30: error: expected ')' before ':' token
object.cc:1343:30: error: expected primary-expression before ':' token
object.cc:1344:79: error: expected primary-expression before ')' token
                                {{CODE,code},{DATA,data},{BSS,bss},{ZERO,zero}})
                                                                               ^
object.cc: In member function 'void Object::WriteRAW(FILE*, unsigned int, unsigned int)':
object.cc:1422:40: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]
             ftruncate(fileno(fp), size);
                                        ^
object.cc: At global scope:
object.cc:819:10: warning: 'void {anonymous}::PutCustomHeader(FILE*, int, int, int)' defined but not used [-Wunused-function]
     void PutCustomHeader(std::FILE* fp, int type, int param1, int param2)
          ^
<builtin>: recipe for target 'object.o' failed
make: *** [object.o] Error 1

**Comment by bisqwit** [comment]
You did not specify which Ubuntu version. In any case, your compiler is too old and does not support C++17 [structured bindings](https://en.cppreference.com/w/cpp/language/structured_binding). You [need](https://gcc.gnu.org/projects/cxx-status.html) GCC version 7 or newer. According to https://packages.ubuntu.com/search?keywords=gcc-7, it is available in Ubuntu at releases starting at Bionic.
