### ISSUE TITLE
Very minor typo

### ISSUE THREAD

**Issue by xotmatrix** [bisqwit/nescom#4]
I didn't want to create a PR for such a minor thing. A comment in `clever.cc` reads:
`        // $A0 y A0 x CA D0 FD 88 D0 FA  XY-delay = opposite`
... it should be:
`        // $A0 y A2 x CA D0 FD 88 D0 FA  XY-delay = opposite`

https://github.com/bisqwit/nescom/blob/70e654904cd86078a23f436bbf6ac5dc900e3cb2/clever.cc#L1487

The delay loop templates are indeed clever.

**Comment by bisqwit** [comment]
Thank you!
